server:
  port: 9012
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: xiaoliyang
    password: 905959759123
    driver-class-name: com.mysql.cj.jdbc.Driver